baseURL = 'https://yumin00.github.io/blog/'
languageCode = 'ko-kr'
title = 'yumin blog'
theme = 'tranquilpeak'

[[menu.main]]
weight = 1
identifier = "home"
name = "Home"
pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
url = "/"
[[menu.main]]
weight = 2
identifier = "categories"
name = "Categories"
pre = "<i class=\"sidebar-button-icon fas fa-lg fa-bookmark\" aria-hidden=\"true\"></i>"
url = "/categories"
[[menu.main]]
weight = 3
identifier = "tags"
name = "Tags"
pre = "<i class=\"sidebar-button-icon fas fa-lg fa-tags\" aria-hidden=\"true\"></i>"
url = "/tags"
[[menu.main]]
weight = 4
identifier = "posts"
name = "Post"
pre = "<i class=\"sidebar-button-icon fas fa-lg fa-archive\" aria-hidden=\"true\"></i>"
url = "/posts"
[[menu.main]]
weight = 5
identifier = "about"
name = "About"
pre = "<i class=\"sidebar-button-icon fas fa-lg fa-question\" aria-hidden=\"true\"></i>"
url = "/#about"

[[menu.links]]
weight = 0
identifier = "github"
name = "GitHub"
pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
url = "https://github.com/kakawait"
[[menu.links]]
weight = 1
identifier = "stackoverflow"
name = "Stack Overflow"
pre = "<i class=\"sidebar-button-icon fab fa-lg fa-stack-overflow\" aria-hidden=\"true\"></i>"
url = "https://stackoverflow.com/users/636472/kakawait"

[[menu.misc]]
weight = 0
identifier = "rss"
name = "RSS"
pre = "<i class=\"sidebar-button-icon fas fa-lg fa-rss\" aria-hidden=\"true\"></i>"
url = "/index.xml"

[params.header.rightLink]
class = "open-algolia-search"
icon = "search"
url = "/#search"

[author]
name = "yumin"
job = "yumin"
location = "Korea"
# Your Gravatar email. Overwrite `author.picture` everywhere in the blog
gravatarEmail = "imeumine8869@naver.com"
# Your profile picture
# Overwritten by your gravatar image if `author.gravatarEmail` is filled
picture = "https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png"

[params]
sidebarBehavior = 1
thumbnailImage = true
thumbnailImagePosition = "right"
autoThumbnailImage = true
coverImage = "images/cover.jpg"
imageGallery = true
hierarchicalCategories = true
syntaxHighlighter = 'highlight.js'

[taxonomies]
tag = "tags"
category = "categories"
categories = ["foo", "bar"]
